# Generated by Django 5.0.6 on 2024-05-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='goles_local',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_visitante',
            field=models.PositiveIntegerField(),
        ),
    ]
