# Generated by Django 5.0.6 on 2024-05-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0002_alter_partido_goles_local_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_local',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_visitante',
            field=models.IntegerField(),
        ),
    ]
